# Generated by Django 3.1.1 on 2020-09-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obraz',
            name='on_main',
            field=models.BooleanField(default=False),
        ),
    ]
