# Generated by Django 3.1.1 on 2020-09-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_obraz_on_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='obraz',
            name='main_img',
            field=models.ImageField(default=None, null=True, upload_to='static/uploads/art'),
        ),
    ]
