# Generated by Django 3.1 on 2020-08-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciuch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('size', models.CharField(max_length=4)),
                ('description', models.TextField(max_length=1000)),
                ('main_img', models.ImageField(default=None, null=True, upload_to='uploads/user/')),
            ],
        ),
    ]
