# Generated by Django 3.1 on 2020-08-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vintage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciuch',
            name='main_img',
            field=models.ImageField(default=None, null=True, upload_to='static/uploads/vintage'),
        ),
    ]
